name: WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    # lancement tous les lundis à 6h45 (CET/CEST)
    - cron: "45 6 * * 1"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          TIME_RANGE: last_year
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          COMMIT_MESSAGE: Mise à jour hebdomadaire stats WakaTime
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          IGNORED_LANGUAGES: Binary
